update readme.md
hacf-fr/awesome-francophone-home-assistant pull request #19
Opened 2020-10-28 21:27 UTC by clemalex824

- Orthographic correction
- french instead of english terms

2020-10-28 21:31 UTC, clemalex824 commented
Error on Table of Contents : 
Can you explain me why readme must have 'Content' term instead of 'Sommaire' ?

2020-10-28 21:51 UTC, oncleben31 requested changes
Thank you for taking time to fix typos and grammatical mistakes. 
Some corrections to be almost perfect ;-)

2020-10-28 21:51 UTC, oncleben31 commented on readme.md
> +## Sommaire
`Contents` section is mandatory to be compliant with awesome list requirement and being in the future referenced in the [master awesome list ](https://github.com/sindresorhus/awesome#readme)

I know it's not ideal for having a full list in French

2020-10-28 21:51 UTC, oncleben31 commented on readme.md
> +_Home Assitant supporte dès la première installation de nombreux équipement ou services liés à la maison connectée. Vous pouvez compléter les intégrations disponibles avec des modules tiers._
```suggestion
_Home Assitant supporte dès la première installation de nombreux équipements ou services liés à la maison connectée. Vous pouvez compléter les intégrations disponibles avec des modules tiers._
```

2020-10-28 21:51 UTC, oncleben31 commented on readme.md
> +Le contenu de Paradis Artificiels est particulier. Ca a été un des premiers fédérateurs populaire de la communauté francophone de Home Assitant et nombreux d'entre nous en sont reconnaissants. Cepend
```suggestion
Le contenu de Paradis Artificiels est particulier. Ca a été un des premiers fédérateurs populaire de la communauté francophone de Home Assitant et nombreux d'entre nous en sont reconnaissants. Cependant nous n'avons plus aucune nouvelle depuis début 2019 et les outils qu'il a mis en place ne peuvent plus être maintenus comme il le faudrait.
```

2020-10-30 18:17 UTC, oncleben31 approved these changes

2020-10-30 18:19 UTC, oncleben31 commented on readme.md
> +## Contents (Table des matières)
```suggestion
## Contents
```

2020-10-30 18:21 UTC, oncleben31 approved these changes

2020-10-30 18:21 UTC, oncleben31 commented
Thank you @clemalex824

2020-10-30 18:21 UTC, merged