Update readme.md
hacf-fr/awesome-francophone-home-assistant pull request #20
Opened 2020-10-28 21:29 UTC by clemalex824

- add deCONZ blog

2020-10-28 21:41 UTC, oncleben31 requested changes
We could improve the link title

2020-10-28 21:41 UTC, oncleben31 commented on readme.md
> +- [Présentation/Configuration de deCONZ](https://presentationdeconz.wordpress.com/) - Tutoriel pour la configuration de deCONZ (Passerelle universelle Zigbee).
Difficult to take the blog name. What do you think of that ?
```suggestion
- [Présentation et guide d'utilisation de deCONZ](https://presentationdeconz.wordpress.com/) - Tutoriel pour la configuration de deCONZ (Passerelle universelle Zigbee).
```

2020-10-28 21:43 UTC, Quentame approved these changes

2020-10-30 18:24 UTC, oncleben31 approved these changes

2020-10-30 18:24 UTC, oncleben31 approved these changes

2020-10-30 18:25 UTC, merged