add [prixCarburant] component
hacf-fr/awesome-francophone-home-assistant pull request #27
Opened 2020-10-30 22:51 UTC by clemalex824

with the author's consent (https://forum.hacf.fr/t/recuperer-les-prix-de-carburants/644)

2020-10-30 22:54 UTC, clemalex824 reviewed
Add ponctuation

2020-10-30 23:22 UTC, oncleben31 requested changes

2020-10-30 23:22 UTC, oncleben31 commented on readme.md
> +- [prixCarburant](https://github.com/max5962/prixCarburant-home-assistant) - Permet de récupérer les prix du carburant depuis le site gouvernemental.
Nous adressons à tous les francophones. Je propose de préciser que c'est les données pour la France
```suggestion
- [prixCarburant](https://github.com/max5962/prixCarburant-home-assistant) - Permet de récupérer les prix du carburant depuis le site gouvernemental français.
```

2020-10-31 00:17 UTC, oncleben31 approved these changes

2020-10-31 00:17 UTC, merged

2020-10-31 00:18 UTC, oncleben31 commented
Thank you 🎉