Ajout catégorie DIY
hacf-fr/awesome-francophone-home-assistant pull request #64
Opened 2020-11-26 12:56 UTC by Squale76

pour répondre à la demande de @oncleben31 dans le post [Téléinfo via wifi](https://forum.hacf.fr/t/teleinfo-via-wifi/1077/12), j'ai ajouté une catégorie **Faites le vous même** et un lien vers un article vers un projet.

2020-11-26 13:25 UTC, oncleben31 requested changes
Merci pour ta contribution.

Quelques demandes de modification ci-dessous avant de pouvoir aboutir.

2020-11-26 13:25 UTC, oncleben31 commented on README.md
> +
Je pense que l'on pourrait y déplacer le blog `Projets DIY`.
Cela pourrait être dans cette PR ou dans une PR dédiée.

2020-11-26 13:25 UTC, oncleben31 commented on README.md
> +## Faites le vous même
Bonne idée d'ajouter une nouvelle catégorie dédiée. Il faudrait mettre à jour la table des matière en cohérence.

2020-11-26 13:25 UTC, oncleben31 commented on README.md
> +- [Alimentation autonome solaire pour petit projet életronique](https://lofurol.fr/joomla/electronique/143-alimentation-autonome-de-petits-projets-electroniques)
J'aimerai que l'on garde de la cohérence avec le modèle Titre - Description.

Par exemple.

```suggestion
- [Alimentation autonome solaire pour petit projet életronique](https://lofurol.fr/joomla/electronique/143-alimentation-autonome-de-petits-projets-electroniques) - Guide pour alimenter un microcontrôleur avec une batterie et un panneau solaire.
```

2020-11-28 07:36 UTC, Squale76 commented on README.md
> +
OK, tu aurais l'adresse du blog `projets DIY` pour l'ajouter dans une future PR

2020-11-28 07:50 UTC, Squale76 commented on README.md
> +## Faites le vous même
Je l'ai ajouté dans le commit [1b0be8f](https://github.com/hacf-fr/awesome-francophone-home-assistant/pull/64/commits/1b0be8fd20b0fcd7da445c8128fe8b2b6643660f)

2020-11-28 07:51 UTC, oncleben31 commented on README.md
> +
Il est déjà dans la liste dans la section blog.

2020-11-28 07:51 UTC, Squale76 commented on README.md
> +- [Alimentation autonome solaire pour petit projet életronique](https://lofurol.fr/joomla/electronique/143-alimentation-autonome-de-petits-projets-electroniques)
Je l'ai ajouté dans le commit [fe72133](https://github.com/hacf-fr/awesome-francophone-home-assistant/pull/64/commits/fe72133a47b89e901eb1617e5c44c667afe36441)

2020-11-28 07:53 UTC, oncleben31 commented on README.md
> +## Faites le vous même
OK merci.

2020-11-28 07:56 UTC, oncleben31 approved these changes

2020-11-28 07:56 UTC, merged