Ajout du blog Faire soi-même
hacf-fr/awesome-francophone-home-assistant pull request #68
Opened 2020-12-07 13:11 UTC by Squale76

Suite à l'issue #63

2020-12-07 13:24 UTC, oncleben31 requested changes
Il y a un problème je vois la même modification que ta dernière PR #64

2020-12-07 17:54 UTC, Squale76 commented
La nouvelle PR concerne la ligne 21 et 39.
Les lignes 71 à 77 ont été déjà acceptées dans la PR #64 

Comme si mon fork n'avait pas été mis à jour suite à l'acceptation de la PR #64. Il y a quelques chose à faire sur mon Github ?

2020-12-07 18:18 UTC, oncleben31 commented
Oui ca s'appelle un rebase.
1 - Tu récupère le dernier état de la branch main sur le dépôt d'origine (upstream)
`git fetch upstream main`

2 - Tu appliques les modifications dans la branche main de ton fork
```
git switch main
git rebase upstream/main
```

Tu peux ensuite créer ta branche de modification et faire tes modification.
Si tu ne veux pas reparti de zéro. Tu peux faire le git rebase upstream/main depuis ta branche de développement existante. S'il y a des conflits il te demandera de les régler à la main.

2020-12-07 18:19 UTC, oncleben31 commented
Au passage je le mettrai plutot dans la section faites le vous même.

2020-12-07 18:36 UTC, oncleben31 commented
J'ai supprimé mon commentaire je t'ai répondu comme si tu faisais du git en local sur ta machine.
En fait il ne faut pas repartir de ton fork. Il faut retourner sur le dépôt initial et cliquer sur édit il crérra une branche à partir de la dernière version de main pour y faire tes modifications.

2020-12-08 06:58 UTC, oncleben31 commented
Refaite dans #69

2020-12-08 06:58 UTC, closed without merging