Add Squale76 configuration
hacf-fr/awesome-francophone-home-assistant pull request #83
Opened 2020-12-29 03:49 UTC by Squale76

2020-12-29 06:53 UTC, oncleben31 requested changes
Merci pour ta contribution. J'apprécie beaucoup d'avoir des configuration partagées sur GitHub de la part de francophone.
En revanche tu mixes deux types de modification: la table des matière et l'ajout d'un lien. Idéalement il faudrait deux PR distinctes.

J'ai quelques remarques sur ton lien. il faudrait aussi penser à ajouter une description et les mot clés dans la partie `about` de ton dépot GitHub pour faciliter la visibilité lors de recherche.

2020-12-29 06:53 UTC, oncleben31 commented on README.md
> +- [Table des matières](#table-des-matières)
Les exigences du format *awesome list* ne recommandent pas d'ajouter cette entrée dans la table des matière.
```suggestion
```

2020-12-29 06:53 UTC, oncleben31 commented on README.md
> +- [Contribuer](#contribuer)
Les exigences du format *awesome list* ne recommandent pas d'ajouter cette entrée dans la table des matière.
```suggestion
```

2020-12-29 06:53 UTC, oncleben31 commented on README.md
> -  - [Paradis Artificiels](#paradis-artificiels)
Merci de veiller à la cohérence de la table des matière. En revanche il serait préférable de faire deux PR distincte. Une pour la mise en forme. Et l'autre pour l'ajout du lien.

2020-12-29 06:53 UTC, oncleben31 commented on README.md
> +- [Squale76](https://github.com/Squale76/home-assistant-configuration/tree/main/config) - Configuration découpée en plusieurs fichiers et documentée au maximum en français.
Je te propose de mettre le lien vers la racine de ton dépot GitHub car en suivant le lien il n'y a aucune documentation même pas un readme.

Et compte tenu d'une lecture rapide de ton dépôt. Je ne vois pas beaucoup de documentation. Je ne comprend donc pas le "documenté au maximum".

2020-12-31 06:20 UTC, oncleben31 commented on README.md
> -  - [Paradis Artificiels](#paradis-artificiels)
J'ai intégré ta proposition dans #90. Tu peux donc les supprimer de cette PR.

2020-12-31 19:04 UTC, Squale76 commented
Je suis perdu sur Guthub. Je suis d'accord avec toutes tes modifications mais j'ai du mal avec l'interface et comment je peux accepter toutes tes évolutions sans faire d'erreurs.
Pour la documentation "documenté au maximum", je voulais à l'origine y mettre un smiley mais j'ai effacer le smiley sans effacer le texte …

2021-01-04 12:06 UTC, oncleben31 commented
Quand il y a une correction de proposée tu peux l'accepter en cliquant sur `commit suggestion`.

Sinon tu retournes dans l'onglet `Files changed` et  `...` / `Edit file` et tu modifies le fichier.

2021-01-05 18:58 UTC, Squale76 commented on README.md
> +- [Squale76](https://github.com/Squale76/home-assistant-configuration/tree/main/config) - Configuration découpée en plusieurs fichiers et documentée au maximum en français.
Je l'ai modifié dans le dernier commit

2021-01-06 17:48 UTC, oncleben31 approved these changes

2021-01-06 17:48 UTC, merged